[package]
name = "prpr-player"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
macroquad = { version = "*", default-features = false }
prpr = { path = "../prpr" }
serde_yaml = "0.9"
