[package]
name = "prpr-player"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
# macroquad = { version = "*", default-features = false }
macroquad = { path = "../../macroquad", default-features = false }
prpr = { path = "../prpr" }
image = "*"
fastblur = "*"
serde_yaml = "0.9"
tokio = "*"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = "*"
wasm-bindgen = "*"
