[package]
name = "prpr-player"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
egui-miniquad = "0.13"
egui = "*"
macroquad = { version = "*", default-features = false }
# macroquad = { path = "../../macroquad", default-features = false }
prpr = { path = "../prpr" }
serde_yaml = "0.9"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = "*"
wasm-bindgen = "*"
