[package]
name = "prpr-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
anyhow = "1.0"
image = "*"
lyon = "*"
macroquad = { version = "*", default-features = false }
# macroquad = { path = "../../macroquad", default-features = false }
once_cell = "*"
prpr = { path = "../prpr" }
reqwest = "0.11"
serde = { version = "*", features = ["derive"] }
openssl = { version = "*", features = ["vendored"] }
serde_json = "*"
tokio = { version = "*", features = ["rt-multi-thread"] }
tempfile = "3.3"

[target.'cfg(not(target_os = "android"))'.dependencies]
nfd = "0.0.4"

[target.'cfg(target_os = "android")'.dependencies]
ndk-sys = "0.2"
ndk-context = "0.1"
