[package]
name = "prpr-android"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
anyhow = "1.0"
macroquad = { path = "../../macroquad", default-features = false }
ndk-sys = "*"
once_cell = "1.16.0"
prpr = { path = "../prpr" }
serde_yaml = "0.9"
