[package]
name = "prpr-render"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
# macroquad = { version = "*", default-features = false }
macroquad = { path = "../../macroquad", default-features = false }
prpr = { path = "../prpr" }
serde_yaml = "0.9"
